services:
  rabbitmq:
    build:
      context: ./middleware/rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
      #- "5672:5672" # conexión AMQP (que usa Pika por ejemplo, pero creo que si dockerizamos todo y creamos una red del tp esto no es necesario)
    networks:
      - coffee_analysis_net
  app_controller:
    build:
      context: .
      dockerfile: app_controller/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - CONFIG_PATH=/config/config.ini
    volumes:
      - ./app_controller/config/config.ini:/config/config.ini:ro
    networks:
      - coffee_analysis_net
  filter_year:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    environment:
      - FILTER_TYPE=Year
      - RESULT_QUEUE=filters_hour
    depends_on:
      - rabbitmq
    networks:
      - coffee_analysis_net
  filter_hour:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    environment:
      - FILTER_TYPE=Hour
      - RESULT_QUEUE=filters_amount
    depends_on:
      - rabbitmq
    networks:
      - coffee_analysis_net
  filter_amount:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - FILTER_TYPE=Amount
      - RESULT_QUEUE=coffee_results
    networks:
      - coffee_analysis_net

networks:
  coffee_analysis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
