services:
  rabbitmq:
    build:
      context: ./middleware/rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    networks:
      - coffee_analysis_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
#  ---------------------------------------
  app_controller:
    build:
      context: .
      dockerfile: app_controller/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_year:
        condition: service_started
    environment:
      - CONFIG_PATH=/config/config.ini
      - STORAGE_DIR=/storage
    volumes:
      - ./app_controller/config/config.ini:/config/config.ini:ro
      - ./app_controller/storage:/storage
    networks:
      - coffee_analysis_net
#  ---------------------------------------
  filter_year:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    environment:
      - FILTER_TYPE=Year #esto puede no estar y usar el routing-key
      - QUEUE_NAME=filter_year_q
      - INPUT_BINDINGS=[["input_file_ex","direct","transactions"],["input_file_ex","direct","transaction_items"]]
      - OUTPUT_EXCHANGE=filter_year_ex
      - OUTPUT_RKS=["transactions", "transaction_items"]
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - coffee_analysis_net
#  ---------------------------------------
  filter_hour:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    environment:
      - FILTER_TYPE=Hour
      - QUEUE_NAME=filter_hour_q
      - INPUT_BINDINGS=[["filter_year_ex","direct","transactions"],["join_stores_ex","direct","stores_joined"]]
      - OUTPUT_EXCHANGE=filter_hour_ex
      - OUTPUT_RKS=["transactions", "store_transactions"]
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - coffee_analysis_net
#  --------------------------------------- Filter Q1
  filter_amount:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - FILTER_TYPE=Amount
      - QUEUE_NAME=filter_amount_q
      - INPUT_BINDINGS=[["filter_hour_ex","direct","transactions"]]
      - OUTPUT_EXCHANGE=results_ex
      - OUTPUT_RKS=["q_amount_75_tx"]
    networks:
      - coffee_analysis_net
#  --------------------------------------- JOIN DE Q3
  join_stores:
    build:
      context: .
      dockerfile: workers/join/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - JOIN_TYPE=Store
      - QUEUE_NAME=join_store_q
      - INPUT_BINDINGS=[["input_file_ex","direct","stores"],["filter_year_ex","direct","transactions"]]
      - OUTPUT_EXCHANGE=join_stores_ex
      - OUTPUT_RKS=["stores_joined", "reduce_user_purchases"]
      - STORAGE_DIR=/storage
    volumes:
      - ./storage:/storage
    networks:
      - coffee_analysis_net
#  --------------------------------------- MAP de Q3
  map_year_half:
    build:
      context: .
      dockerfile: workers/map/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MAP_TYPE=YearHalf
      - QUEUE_NAME=map_year_half_q
      - INPUT_BINDINGS=[["filter_hour_ex","direct","store_transactions"]]
      - OUTPUT_EXCHANGE=map_year_half_ex
      - OUTPUT_RKS=["map_half"]
    networks:
      - coffee_analysis_net
#  --------------------------------------- REDUCE Q3
  reduce_tpv:
    build:
      context: .
      dockerfile: workers/reduce/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - REDUCE_TYPE=tpv
      - QUEUE_NAME=reduce_tpv_q
      - INPUT_BINDINGS=[["map_year_half_ex","direct","map_half"]]
      - OUTPUT_EXCHANGE=results_ex
      - OUTPUT_RKS=["q_semester_tpv"]
    networks:
      - coffee_analysis_net
networks:
  coffee_analysis_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
